Refactor de la clase OtherInfoWindow
elagarrigue/AyDS23-NewYork1 pull request #2
Opened 2023-04-26 20:05 UTC by agusdeba

Ro, con Lucio hicimos refactor en la clase OtherInfoWindow, modularizamos el metodo getArtistInfo y pensamos que se podría crear el gSon en otro método y sus atributos correspondientes (jObj, responseObj, docsElement y url) tenerlos como atributos globales. De esta manera se reduciría la tarea de dicho método, seria mas legible y podríamos entender mejor que hace el código.

2023-04-27 00:48 UTC, Lucio-Lorenzetti requested changes
Ro revisando el código, por ahí noté que el método "testDataBase()" es innecesario, y ademas de eso, por ahí para el método "addItems()" se podría aprovechar alguna función propia de Java, dejando eso de lado, el código se nota muy claro y legible, está bien modularizado y es sencillo de entender debido a los cambios que realizaste

2023-04-29 18:55 UTC, elagarrigue commented
Los reviewers del branch de entrega tenemos que ser  los miembros de la cátedra, no uds

2023-05-02 18:43 UTC, kevschweitzer requested changes

2023-05-02 18:43 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun findViewByID(urlString: String) {
Mal nombre. Puede ser setListener. El findViewById ponganlo como propiedad

2023-05-02 18:43 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            builder.append("<html><div width=400>")
Definir constantes para los codigos html

2023-05-02 18:43 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/DataBase.kt
> +                "id",
Definir constantes para nombres de columnas

2023-05-04 01:43 UTC, kevschweitzer requested changes

2023-05-04 01:43 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                loadAndSet(artistName)
Cuando un metodo dice AND ya se entiende que hace 2 cosas. Cambiar el nombre. 
Además, si hacemos un nuevo thread y despues llamamos a runOnUiThread es lo mismo que no crear el thread porque siempre lo hace en el main Thread. La idea es usar runOnUiThread solo en los set de la vista que es donde realmente se necesita

2023-05-04 01:43 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun loadAndSet(artistName: String?) {
No hicieron lo de crear un nuevo objeto para tener los datos del artist
Este metodo deberia quedarles algo asi
```
fun updateMoreDetails(artistName: String?) {
        val artist = getArtistInfo(artistName) 
       updateView(artist)
}

Artist seria de tipo ArtistInfo que es la clase de datos que les dije que tenian que crear.
Por otro lado la función getArtistInfo() deberia ser IDENTICO al algoritmo de la clase repository que esta en home, es decir

1. Buscar en la BD
2. Si esta en la BD marcar como local y retornar
3. Si no esta en la BD buscar en la API
4. Si la encuentra guardar en BD y retornar

2023-05-05 19:39 UTC, merged